Render Props => Technique => sharing code b/w React Component, using a prop that is a function

- Takes a fcn taht returns a Reat element and call its instead of implementing its own render logic


Anon Functions vs Functions

https://stackoverflow.com/questions/42571091/react-performance-anonymous-function-vs-named-function-vs-method/42571147
- function vs PureFunction


https://medium.com/@stevemao/do-not-use-anonymous-functions-to-construct-react-functional-components-c5408ec8f4c7
https://stackoverflow.com/questions/37288950/why-does-the-airbnb-style-guide-say-that-relying-on-function-name-inference-is-d

LOL i forgot about the hoisting. I need to a fresher onthat